### ISSUE TITLE
cached bind-mount Docker volume setting is not recognised

### ISSUE THREAD

**Issue by dvejmz** [emk/compose_yml#19]
This affects cage, as described in https://github.com/faradayio/cage/issues/104.

Using this issue to track the work I intend to be doing against this. The gist of the change is to add support for "long syntax" cached bind-mounted Docker volume definitions [here](https://github.com/emk/compose_yml/blob/master/src/v2/volume_mount.rs) so that this option is recognised when parsing docker-compose files.

**Comment by emk** [comment]
This should be fixed in `master`. Thank you for the PR!
