### ISSUE TITLE
Upgrade to Serde 1.0

### ISSUE THREAD

**Issue by dtolnay** [emk/compose_yml#7]
I think the most important reason for this library would be better error messages.

#### Serde 0.8

>  Invalid type. Expected \`Bool\`

#### Serde 0.9

> font.use_thin_strokes: invalid type: string "tru", expected a boolean at line 51 column 21

---

Release notes: https://github.com/serde-rs/serde/releases/tag/v0.9.0

**Comment by emk** [comment]
Oh, thank goodness! I'm so happy to see those new error messages. I'll put this on my list; I'm ridiculously backlogged with Rust stuff right now.

**Comment by emk** [comment]
OK, current status: work on `cage` has been delayed for another month because of an internal Rust project, and `cage` depends on `compose_yml`, so this is unlikely to see any changes for another month.

**Comment by emk** [comment]
Unfortunately, it looks like upgrading to serde 1.0 will break some important features, because `valico` is still stuck on serde 0.8, and it's the only Rust library for JSON schema validation at the moment.

**Comment by emk** [comment]
See #11 and https://github.com/rustless/valico/pull/27 for more info on the `valico` situation.
